import Head from 'next/head'
import Header from '../../components/header'
import moment from 'moment'

export default function Home({ DATA }) {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>EPG Viewer</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <Header />
    </div>
  )
}

Home.getInitialProps = async ({ query }) => {
  const { channel } = query

  const data = await fetch(
    `http://localhost:8000/api/data/${moment().format('YYYY-MM-DD')}/${channel}`
  )
  const json = await data.json()
  const arr = []

  Object.entries(json.data).forEach(registro => {
    arr.push({
      CODIGO: registro[1].DATOS_CADENA.CODIGO,
      MARCA: registro[1].DATOS_CADENA.MARCA,
      NOMBRE: String(registro[1].DATOS_CADENA.NOMBRE),
      DIAL_PRINCIPAL: registro[1].DATOS_CADENA.DIAL_PRINCIPAL,
    })
  })

  return {
    DATA: arr,
  }
}
