import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home({ DATA }) {
  return (
    <div className="bg-gray-100">
      <Head>
        <title>EPG Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex p-8 flex-col items-center justify-center">
        <h1 className="text-3xl font-bold underline text-cyan-800 m-4">
          Lista de Canales 😎
        </h1>
        <ul className='grid gap-1 grid-cols-5 grid-rows-auto'>
          {
            DATA.map((d, key) => (
              <li
                key={key}
                className="flex flex-col justify-center items-center text-xs capitalize font-semibold mb-4"
              >
                <Image
                  width={50}
                  height={50}
                  objectFit='contain'
                  src={'https://www.movistarplus.es/recorte/m-NEO/canal/' + d.CODIGO + '.png'}
                />
                <span className='mt-1'>
                  {d.NOMBRE} | {d.DIAL_PRINCIPAL[0]}
                </span>
              </li>
            ))
          }
        </ul>
      </main>
    </div>
  )
}

Home.getInitialProps = async () => {
  const data = await fetch('http://localhost:3000/api/data/20220215')
  const json = await data.json()
  let arr = []

  Object.entries(json.data).forEach(registro => {
    arr.push({
      CODIGO: registro[1].DATOS_CADENA.CODIGO,
      MARCA: registro[1].DATOS_CADENA.MARCA,
      NOMBRE: registro[1].DATOS_CADENA.NOMBRE,
      DIAL_PRINCIPAL: registro[1].DATOS_CADENA.DIAL_PRINCIPAL
    })
  })
  
  return {
    DATA: arr
  }
}