import Head from 'next/head'
import Image from 'next/image'
import Header from '../components/header'
import moment from 'moment'
import Link from 'next/link'

export default function Home({ DATA }) {
  return (
    <div className='bg-gray-100'>
      <Head>
        <title>EPG Viewer</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>

      <Header />

      <main className='flex flex-col items-center justify-center'>
        <h1 className='mb-8 text-3xl font-bold text-cyan-800 underline'>
          Listado
        </h1>
        <ul className='grid-rows-auto grid grid-cols-3 gap-1'>
          {DATA.map((d, key) => (
            <li
              key={key}
              className='justify-left mb-4 flex items-center text-xs font-semibold capitalize'
            >
              <Link
                href={`/detail/${d.CODIGO}`}
                passHref
              >
                <a className='flex content-center'>
                  <Image
                    width={25}
                    height={25}
                    objectFit='contain'
                    src={
                      'https://www.movistarplus.es/recorte/m-NEO/canal/' +
                      d.CODIGO +
                      '.png'
                    }
                    alt={`image of ${d.CODIGO}`}
                  />
                  <span className='m-1'>
                    {d.NOMBRE} | {d.DIAL_PRINCIPAL[0]}
                  </span>
                </a>
              </Link>
            </li>
          ))}
        </ul>
      </main>
    </div>
  )
}

Home.getInitialProps = async () => {
  const data = await fetch(
    `http://localhost:8000/api/data/${moment().format('YYYY-MM-DD')}`
  )
  const json = await data.json()
  const arr = []

  Object.entries(json.data).forEach(registro => {
    arr.push({
      CODIGO: registro[1].DATOS_CADENA.CODIGO,
      MARCA: registro[1].DATOS_CADENA.MARCA,
      NOMBRE: String(registro[1].DATOS_CADENA.NOMBRE),
      DIAL_PRINCIPAL: registro[1].DATOS_CADENA.DIAL_PRINCIPAL,
    })
  })

  return {
    DATA: arr,
  }
}
